// Generate a random project name
const generateRandomName = () => {
  const adjectives = [
    "swift",
    "brave",
    "bright",
    "cosmic",
    "dynamic",
    "elegant",
    "fierce",
    "golden",
    "hidden",
    "infinite",
    "jovial",
    "keen",
    "lively",
    "mystic",
    "noble",
    "optimal",
    "prime",
    "quantum",
    "radiant",
    "stellar",
    "agile",
    "balanced",
    "calm",
    "dazzling",
    "emerald",
    "focused",
    "glacial",
    "harmonic",
    "iconic",
    "jade",
    "kinetic",
    "lucid",
    "magnetic",
    "nimble",
    "oceanic",
    "powerful",
    "quirky",
    "resilient",
    "sapphire",
    "tactical",
    "unified",
    "vibrant",
    "wild",
    "xenial",
    "yielding",
    "zealous",
    "astral",
    "bold",
    "crystal",
    "daring",
    "electric",
    "fluent",
    "grand",
    "hybrid",
    "inspired",
  ];

  const nouns = [
    "aurora",
    "beacon",
    "cascade",
    "delta",
    "echo",
    "falcon",
    "galaxy",
    "horizon",
    "impulse",
    "journey",
    "kingdom",
    "legacy",
    "meridian",
    "nexus",
    "orbit",
    "phoenix",
    "quasar",
    "reef",
    "summit",
    "tempest",
    "atlas",
    "bastion",
    "cipher",
    "domain",
    "ember",
    "fortress",
    "genesis",
    "haven",
    "icon",
    "jewel",
    "karma",
    "labyrinth",
    "matrix",
    "nebula",
    "oasis",
    "prism",
    "quest",
    "reactor",
    "sanctuary",
    "titan",
    "unity",
    "venture",
    "wisdom",
    "xylon",
    "yard",
    "zenith",
    "aether",
    "bridge",
    "citadel",
    "dawn",
    "eclipse",
    "flux",
    "grove",
    "harbor",
    "infinity",
  ];

  const randomAdjective =
    adjectives[Math.floor(Math.random() * adjectives.length)];
  const randomNoun = nouns[Math.floor(Math.random() * nouns.length)];
  return { randomNoun: randomNoun, randomAdjective: randomAdjective };
};

export default generateRandomName;
